# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Cenfotec-gram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cenfotec-gram
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
  pod 'AmplifyPlugins/AWSS3StoragePlugin'
  pod 'AmplifyPlugins/AWSAPIPlugin'
  pod 'AmplifyPlugins/AWSDataStorePlugin'
  pod 'SCLAlertView'

end
